version: "3"

services:
  voyce:
    build:
      context: ./build
    container_name: application_web
    privileged: true
    volumes:
      - ./supervisor/:/etc/supervisor/conf.d/
      - ./projects:/var/www/html/
      - ./vhost/:/etc/nginx/sites-enabled/
      - ./ssl/certsdesk:/etc/ssl/certsdesk
      - ./ssl/private:/etc/ssl/private
      - ~/.ssh/:/home/docker/.ssh/
    links:
      - "rabbitmq:rabbitmq"
      - "postgres:postgres"
    expose:
      - "80"
    ports:
      - "80:80"
      - "443:443"
      - "1080:1080"
      - "9090:9090"
    command: "/usr/bin/supervisord -n"
    tty: true
    environment:
      - XDEBUG_CONFIG=remote_host=
      - PHP_IDE_CONFIG=serverName=Xdebug
  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: rabbitmq
    privileged: true
    ports:
      - "5672:5672"
      - "15672:15672"
    tty: true
  postgres:
    image: postgres:9.5
    container_name: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - "./volume/postgres/backup:/var/backup/"
      - "./volume/postgres/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    links:
      - "postgres:postgres"
    volumes:
      - "./volume/pgadmin:/var/lib/pgadmin"

